---
- hosts: all
  become: true
  tasks:
    - name: install Apache2 and PHP packages on Ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        update_cache: yes
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install httpd and PHP packages on AlmaLinux
      dnf:
        name: 
          - httpd
          - php
        update_cache: yes
        state: latest
      when: ansible_distribution == "AlmaLinux"
